import json
import urllib.error
import urllib.request

import gradio as gr
import pandas as pd

BASE_URL = "http://localhost:5000"
LOG_COLUMNS = ["type", "content_id", "timestamp", "confidence_score", "label_key", "status", "reasoning"]


def _empty_log_df():
    return pd.DataFrame(columns=LOG_COLUMNS)


def _entries_to_df(entries):
    if not entries:
        return _empty_log_df()
    rows = [{col: e.get(col, "") for col in LOG_COLUMNS} for e in entries]
    return pd.DataFrame(rows, columns=LOG_COLUMNS)


def _post(path, payload):
    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        BASE_URL + path,
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read())
        except Exception:
            return e.code, {}
    except urllib.error.URLError:
        return None, None


def _get(path):
    try:
        with urllib.request.urlopen(BASE_URL + path, timeout=10) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read())
        except Exception:
            return e.code, {}
    except urllib.error.URLError:
        return None, None


def submit_text(text):
    if not text or not text.strip():
        return "Please enter some text.", "", "", "", _empty_log_df()

    status, data = _post("/submit", {"text": text})


    if status is None:
        msg = "Could not connect to server. Is Flask running on localhost:5000?"
        return msg, "", "", "", _empty_log_df()
    if data is None:
        msg = "Data failed to fetch. Please try again."
        return msg
    if status == 429:
        return "Rate limit reached. Please wait a moment.", "", "", "", _empty_log_df()
    if status != 200:
        return data.get("error", "Unknown error."), "", "", "", _empty_log_df()

    return (
        data.get("label_key", ""),
        str(data.get("confidence_score", "")),
        data.get("content_id", ""),
        data.get("label_detail", ""),
        refresh_log(),
    )


def refresh_log():
    status, data = _get("/log")
    if status is None or status != 200:
        return _empty_log_df()
    return _entries_to_df(data)


def submit_appeal(content_id, reasoning):
    if not content_id or not content_id.strip():
        return "Please enter a Content ID."
    if not reasoning or not reasoning.strip():
        return "Please enter your reasoning."

    status, data = _post(
        "/appeal",
        {"content_id": content_id.strip(), "reasoning": reasoning.strip()},
    )


    if status is None:
        return "Could not connect to server. Is Flask running on localhost:5000?"
    if data is None:
        msg = "Data failed to fetch. Please try again."
        return msg
    if status == 429:
        return "Rate limit reached. Please wait a moment."
    if status != 200:
        return data.get("error", "Unknown error.")
    return data.get("message", "Appeal submitted successfully.")


with gr.Blocks(title="Provenance Guard") as demo:
    gr.Markdown("# Provenance Guard\nDetermine whether your content was written by a human or generated by AI.")

    with gr.Tabs():

        # ── Submit tab ──────────────────────────────────────────────────
        with gr.Tab("Submit"):
            with gr.Row():
                with gr.Column(scale=2):
                    text_input = gr.Textbox(
                        lines=10,
                        placeholder="Paste your text here...",
                        show_label=False,
                    )
                    submit_btn = gr.Button("Analyze Text", variant="primary")
                    label_out = gr.Textbox(label="Label", interactive=False)
                    score_out = gr.Textbox(label="Confidence Score", interactive=False)
                    id_out = gr.Textbox(label="Content ID", interactive=False)
                    detail_out = gr.Textbox(label="Detail", interactive=False, lines=3)

                with gr.Column(scale=1):
                    with gr.Accordion("Audit Log", open=False):
                        log_table = gr.Dataframe(
                            value=_empty_log_df(),
                            interactive=False,
                        )
                        refresh_submit_btn = gr.Button("Refresh")

            submit_btn.click(
                fn=submit_text,
                inputs=[text_input],
                outputs=[label_out, score_out, id_out, detail_out, log_table],
            )
            refresh_submit_btn.click(fn=refresh_log, inputs=[], outputs=[log_table])

        # ── Appeal tab ──────────────────────────────────────────────────
        with gr.Tab("Appeal"):
            appeal_id = gr.Textbox(
                label="Content ID",
                placeholder="Paste the content_id from your submission",
            )
            appeal_reason = gr.Textbox(
                label="Reasoning",
                lines=4,
                placeholder="Explain why you believe this classification is incorrect",
            )
            appeal_btn = gr.Button("Submit Appeal", variant="primary")
            appeal_result = gr.Textbox(label="Result", interactive=False)

            appeal_btn.click(
                fn=submit_appeal,
                inputs=[appeal_id, appeal_reason],
                outputs=[appeal_result],
            )

        # ── Log tab ─────────────────────────────────────────────────────
        with gr.Tab("Log"):
            refresh_log_btn = gr.Button("Refresh Log")
            log_tab_table = gr.Dataframe(
                value=_empty_log_df(),
                interactive=False,
            )
            refresh_log_btn.click(fn=refresh_log, inputs=[], outputs=[log_tab_table])


if __name__ == "__main__":
    demo.launch()
