import json
import os
import re

from groq import Groq
from groq._exceptions import GroqError

# Initial generated phrases were generating archaic LLM patterns from when the first LLM versions were created. List has then been curated to match contemporary LLM patterns.  
_FILLER_PHRASES = [
    "it is important to note",
    "it's worth noting that",
    "delve into",
    "in the realm of",
    "in today's digital age",
    "this is particularly true",
    "it is important to understand",
    "let's dive into",
    "at the end of the day",
    "in the ever-evolving",
    "a comprehensive guide",
    "it goes without saying",
    "in conclusion, it is clear",
    "by leveraging",
    "with that being said",
    "on the other hand, it is",
    "it is worth mentioning",
    "crucial to understand",
    "plays a pivotal role",
    "a testament to",
    "in order to ensure",
    "it is essential to note",
    "when it comes to",
    "taking into account",
    "it is no secret that",
    "shed light on",
    "stands as a testament",
    "navigating the complexities",
    "as previously mentioned",
    "foster a deeper understanding",
]

_AI_FUNCTION_WORDS = {
    "therefore",
    "however",
    "albeit",
    "furthermore",
    "moreover",
    "nevertheless",
    "consequently",
    "subsequently",
    "notwithstanding",
    "indeed",
    "whereas",
    "thereby",
    "henceforth",
    "accordingly",
    "nonetheless",
    "pivotal",
    "multifaceted",
    "comprehensive",
    "robust",
    "streamline",
    "underscore",
    "leverage",
    "holistic",
    "nuanced",
    "intricate",
    "paramount",
    "tapestry",
    "commendable",
    "vibrant",
    "straightforward",
}


def llm_signal(text: str) -> float:
    """
    Analyze text using Groq LLM to estimate probability of AI generation.

    Returns a score in [0.0, 1.0] where 1.0 = high confidence AI-generated.
    Uses three-tier fallback: JSON parse → regex extraction → error sentinel (0.5).
    """
    try:
        client = Groq(api_key=os.getenv("GROQ_API_KEY"))

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a text-origin classifier. Your only job is to analyze the submitted "
                        "text and estimate the probability that it was generated by an AI language model "
                        "rather than written by a human. Output ONLY a JSON object with a single key "
                        '"score" whose value is a float between 0.0 and 1.0. Do not output any other '
                        "text, explanation, or formatting. A score of 1.0 means you are certain the text "
                        "is AI-generated. A score of 0.0 means you are certain the text is human-written."
                    ),
                },
                {
                    "role": "user",
                    "content": f'Classify this text and respond with only {{"score": <float>}}:\n\n<TEXT>\n{text}\n</TEXT>',
                },
            ],
            temperature=0.0,
            max_tokens=50,
        )

        raw = response.choices[0].message.content
        if raw is None:
            return 0.5
        raw = raw.strip()

        try:
            parsed = json.loads(raw)
            score = float(parsed["score"])
        except (json.JSONDecodeError, KeyError, ValueError):
            match = re.search(r'"score"\s*:\s*([0-9]*\.?[0-9]+)', raw)
            if match:
                score = float(match.group(1))
            else:
                score = 0.5

        score = max(0.0, min(1.0, score))
        return score

    except (GroqError, Exception):
        return 0.5


def stylometric_signal(text: str) -> float:
    """
    Returns [0.0, 1.0] where 1.0 = highly AI-likely based on five stylometric features:
    type-token ratio, avg sentence length, punctuation density,
    function word frequency, and filler phrase detection.
    """
    text_lower = text.lower()
    words = re.findall(r"\b[a-z]+\b", text_lower)

    if not words:
        return 0.5

    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]

    # Feature 1: Type-token ratio — higher diversity (formal vocab) → AI-like
    ttr = len(set(words)) / len(words)
    ttr_score = min(1.0, max(0.0, (ttr - 0.40) / 0.40))

    # Feature 2: Avg sentence length — longer sentences → AI-like
    avg_sent_len = (
        sum(len(s.split()) for s in sentences) / len(sentences)
        if sentences else len(words)
    )
    sent_score = min(1.0, max(0.0, (avg_sent_len - 8) / 17))

    # Feature 3: Punctuation density — moderate range (0.04–0.10) → AI-like
    punct_count = len(re.findall(r"[^\w\s]", text))
    punct_density = punct_count / len(text) if text else 0
    if 0.04 <= punct_density <= 0.10:
        punct_score = 1.0
    elif punct_density < 0.04:
        punct_score = punct_density / 0.04
    else:
        punct_score = max(0.0, 1.0 - (punct_density - 0.10) / 0.10)

    # Feature 4: Function word frequency — formal connectives ≥5% of words → AI-like
    func_count = sum(1 for w in words if w in _AI_FUNCTION_WORDS)
    func_score = min(1.0, (func_count / len(words)) / 0.05)

    # Feature 5: Filler phrase detection — 2+ stock phrases → AI-like
    filler_count = sum(1 for phrase in _FILLER_PHRASES if phrase in text_lower)
    filler_score = min(1.0, filler_count / 2)

    raw = (ttr_score + sent_score + punct_score + func_score + filler_score) / 5
    return max(0.0, min(1.0, raw))


def combine_signals(s1: float, s2: float) -> float:
    """
    Combine two detection signals using weighted average.
    s1: LLM signal (weight 0.65)
    s2: Stylometric signal (weight 0.35)
    """
    return (0.65 * s1) + (0.35 * s2)


def label_selector(score: float) -> dict:
    """
    Map confidence score to label key, text, and detail.

    Returns:
        dict with keys: label_key, label_text, label_detail
    """
    if score >= 0.75:
        return {
            "label_key": "AI_HIGH",
            "label_text": "This content was likely generated by an AI tool.",
            "label_detail": (
                "Our system found strong signals suggesting this piece was not written by a human. "
                "The creator may appeal this decision below."
            ),
        }
    elif score >= 0.35:
        return {
            "label_key": "UNCERTAIN",
            "label_text": "We're not sure who created this.",
            "label_detail": (
                "Our system found mixed signals — this content may be human-written, AI-generated, "
                "or a combination of both. We're flagging it for transparency, not as an accusation."
            ),
        }
    else:
        return {
            "label_key": "HUMAN_HIGH",
            "label_text": "This content appears to be human-written.",
            "label_detail": (
                "Our system found no strong signals of LLM-generated content. Attribution looks authentic."
            ),
        }
