import json
import os
import re

from groq import Groq
from groq._exceptions import GroqError


def llm_signal(text: str) -> float:
    """
    Analyze text using Groq LLM to estimate probability of AI generation.

    Returns a score in [0.0, 1.0] where 1.0 = high confidence AI-generated.
    Uses three-tier fallback: JSON parse → regex extraction → error sentinel (0.5).
    """
    try:
        client = Groq(api_key=os.getenv("GROQ_API_KEY"))

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a text-origin classifier. Your only job is to analyze the submitted "
                        "text and estimate the probability that it was generated by an AI language model "
                        "rather than written by a human. Output ONLY a JSON object with a single key "
                        '"score" whose value is a float between 0.0 and 1.0. Do not output any other '
                        "text, explanation, or formatting. A score of 1.0 means you are certain the text "
                        "is AI-generated. A score of 0.0 means you are certain the text is human-written."
                    ),
                },
                {
                    "role": "user",
                    "content": f'Classify this text and respond with only {{"score": <float>}}:\n\n<TEXT>\n{text}\n</TEXT>',
                },
            ],
            temperature=0.0,
            max_tokens=50,
        )

        raw = response.choices[0].message.content
        if raw is None:
            return 0.5
        raw = raw.strip()

        try:
            parsed = json.loads(raw)
            score = float(parsed["score"])
        except (json.JSONDecodeError, KeyError, ValueError):
            match = re.search(r'"score"\s*:\s*([0-9]*\.?[0-9]+)', raw)
            if match:
                score = float(match.group(1))
            else:
                score = 0.5

        score = max(0.0, min(1.0, score))
        return score

    except (GroqError, Exception):
        return 0.5


def combine_signals(s1: float, s2: float) -> float:
    """
    Combine two detection signals using weighted average.
    s1: LLM signal (weight 0.65)
    s2: Stylometric signal (weight 0.35)
    """
    return (0.65 * s1) + (0.35 * s2)


def label_selector(score: float) -> dict:
    """
    Map confidence score to label key, text, and detail.

    Returns:
        dict with keys: label_key, label_text, label_detail
    """
    if score >= 0.80:
        return {
            "label_key": "AI_HIGH",
            "label_text": "This content was likely generated by an AI tool.",
            "label_detail": (
                "Our system found strong signals suggesting this piece was not written by a human. "
                "The creator may appeal this decision below."
            ),
        }
    elif score >= 0.40:
        return {
            "label_key": "UNCERTAIN",
            "label_text": "We're not sure who created this.",
            "label_detail": (
                "Our system found mixed signals — this content may be human-written, AI-generated, "
                "or a combination of both. We're flagging it for transparency, not as an accusation."
            ),
        }
    else:
        return {
            "label_key": "HUMAN_HIGH",
            "label_text": "This content appears to be human-written.",
            "label_detail": (
                "Our system found no strong signals of LLM-generated content. Attribution looks authentic."
            ),
        }
