import os
import pytest
from unittest.mock import MagicMock, patch

from signals import llm_signal, combine_signals, label_selector


class TestLLMSignal:
    """Unit tests for llm_signal (all mocked, no real API)."""

    @patch("signals.Groq")
    def test_clean_json_parse(self, mock_groq_class):
        """A1: Clean JSON parse."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            '{"score": 0.92}'
        )

        result = llm_signal("test text")
        assert result == 0.92

    @patch("signals.Groq")
    def test_json_with_whitespace(self, mock_groq_class):
        """A2: JSON with whitespace and newlines."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            '\n{"score": 0.45}\n'
        )

        result = llm_signal("test text")
        assert result == 0.45

    @patch("signals.Groq")
    def test_regex_fallback_malformed_json(self, mock_groq_class):
        """A3: Malformed JSON with embedded score — regex fallback."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            'The score is: {"score": 0.71} based on my analysis.'
        )

        result = llm_signal("test text")
        assert result == 0.71

    @patch("signals.Groq")
    def test_no_parseable_score(self, mock_groq_class):
        """A4: No parseable score in response — sentinel 0.5."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            "score: 0.88"
        )

        result = llm_signal("test text")
        assert result == 0.5

    @patch("signals.Groq")
    def test_groq_error(self, mock_groq_class):
        """A5: GroqError exception — sentinel 0.5."""
        from groq._exceptions import GroqError

        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.side_effect = GroqError("API failure")

        result = llm_signal("test text")
        assert result == 0.5

    @patch("signals.Groq")
    def test_clamp_upper_bound(self, mock_groq_class):
        """A6: Score > 1.0 clamped to 1.0."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            '{"score": 1.5}'
        )

        result = llm_signal("test text")
        assert result == 1.0

    @patch("signals.Groq")
    def test_clamp_lower_bound(self, mock_groq_class):
        """A7: Score < 0.0 clamped to 0.0."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            '{"score": -0.3}'
        )

        result = llm_signal("test text")
        assert result == 0.0

    @patch("signals.Groq")
    def test_missing_score_key(self, mock_groq_class):
        """A8: Missing "score" key in JSON — sentinel 0.5."""
        mock_client = MagicMock()
        mock_groq_class.return_value = mock_client
        mock_client.chat.completions.create.return_value.choices[0].message.content = (
            '{"confidence": 0.88}'
        )

        result = llm_signal("test text")
        assert result == 0.5


class TestCombineSignals:
    """Unit tests for combine_signals."""

    def test_only_s1(self):
        """B1: s1=1.0, s2=0.0 → 0.65."""
        result = combine_signals(1.0, 0.0)
        assert result == 0.65

    def test_only_s2(self):
        """B2: s1=0.0, s2=1.0 → 0.35."""
        result = combine_signals(0.0, 1.0)
        assert result == 0.35

    def test_both_zero(self):
        """B3: s1=0.0, s2=0.0 → 0.0."""
        result = combine_signals(0.0, 0.0)
        assert result == 0.0

    def test_both_one(self):
        """B4: s1=1.0, s2=1.0 → 1.0."""
        result = combine_signals(1.0, 1.0)
        assert result == 1.0

    def test_m3_pipeline_path(self):
        """B5: M3 pipeline path (s2=0.0 always) with s1=0.8."""
        result = combine_signals(0.8, 0.0)
        assert result == pytest.approx(0.52)


class TestLabelSelector:
    """Unit tests for label_selector."""

    def test_ai_high_above_threshold(self):
        """C1: score=0.95 → AI_HIGH."""
        result = label_selector(0.95)
        assert result["label_key"] == "AI_HIGH"
        assert result["label_text"] == "This content was likely generated by an AI tool."
        assert "label_detail" in result

    def test_ai_high_at_boundary(self):
        """C2: score=0.80 (boundary) → AI_HIGH."""
        result = label_selector(0.80)
        assert result["label_key"] == "AI_HIGH"

    def test_uncertain_just_below_ai(self):
        """C3: score=0.79 (just below AI_HIGH) → UNCERTAIN."""
        result = label_selector(0.79)
        assert result["label_key"] == "UNCERTAIN"

    def test_uncertain_middle(self):
        """C4: score=0.60 → UNCERTAIN."""
        result = label_selector(0.60)
        assert result["label_key"] == "UNCERTAIN"
        assert result["label_text"] == "We're not sure who created this."

    def test_uncertain_at_lower_boundary(self):
        """C5: score=0.40 (boundary) → UNCERTAIN."""
        result = label_selector(0.40)
        assert result["label_key"] == "UNCERTAIN"

    def test_human_high_just_below_uncertain(self):
        """C6: score=0.39 (just below UNCERTAIN) → HUMAN_HIGH."""
        result = label_selector(0.39)
        assert result["label_key"] == "HUMAN_HIGH"

    def test_human_high_low_score(self):
        """C7: score=0.10 → HUMAN_HIGH."""
        result = label_selector(0.10)
        assert result["label_key"] == "HUMAN_HIGH"
        assert result["label_text"] == "This content appears to be human-written."

    def test_all_labels_have_required_keys(self):
        """C8: All labels contain required keys."""
        for score in [0.95, 0.60, 0.10]:
            result = label_selector(score)
            assert "label_key" in result
            assert "label_text" in result
            assert "label_detail" in result


class TestIntegration:
    """Integration tests that call the real Groq API."""

    @pytest.mark.skipif(
        not os.getenv("GROQ_API_KEY"),
        reason="GROQ_API_KEY not set — skipping integration tests",
    )
    @pytest.mark.integration
    def test_ai_generated_text_high_score(self):
        """D1: AI-generated text scores > 0.80."""
        ai_text = (
            "Artificial intelligence has revolutionized numerous industries by enabling "
            "machines to perform tasks that previously required human intelligence. "
            "Machine learning algorithms, particularly deep neural networks, have demonstrated "
            "remarkable capabilities in image recognition, natural language processing, and "
            "strategic game playing. Furthermore, it is worth noting that the integration of "
            "AI into healthcare, finance, and transportation sectors has yielded significant "
            "improvements in efficiency and accuracy. In conclusion, the transformative potential "
            "of AI continues to expand as computational resources and algorithmic sophistication "
            "advance in tandem."
        )
        score = llm_signal(ai_text)
        assert (
            score > 0.80
        ), f"Expected AI text to score > 0.80, got {score}"

    @pytest.mark.skipif(
        not os.getenv("GROQ_API_KEY"),
        reason="GROQ_API_KEY not set — skipping integration tests",
    )
    @pytest.mark.integration
    def test_human_written_text_low_score(self):
        """D2: Human-written text scores < 0.35."""
        human_text = (
            "My grandmother never learned to drive. She walked everywhere — to the market, "
            "to church, to my school when she'd forget her umbrella. I used to be embarrassed "
            "by this when I was twelve. Now I think about her shoes, the way she'd pause at "
            "the corner of Elm and Third like she was deciding something important, and I wonder "
            "what it felt like to know a neighborhood that slowly, that intimately."
        )
        score = llm_signal(human_text)
        assert (
            score < 0.35
        ), f"Expected human text to score < 0.35, got {score}"

    @pytest.mark.skipif(
        not os.getenv("GROQ_API_KEY"),
        reason="GROQ_API_KEY not set — skipping integration tests",
    )
    @pytest.mark.integration
    def test_ambiguous_text_middle_score(self):
        """D3: Ambiguous text scores in uncertain range (0.40–0.79)."""
        ambiguous_text = (
            "The city had changed. Marcus noticed it in the way the old coffee shop on 5th "
            "had been replaced by a co-working space, all exposed brick and ergonomic chairs. "
            "Studies suggest that urban gentrification often displaces long-term residents, "
            "though local business owners report mixed outcomes depending on their lease "
            "structures and foot traffic patterns."
        )
        score = llm_signal(ambiguous_text)
        assert (
            0.40 <= score < 0.80
        ), f"Expected ambiguous text to score in uncertain range [0.40–0.79], got {score}"
